In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('heart.csv')

In [3]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [4]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [5]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()
df[['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']] = df[['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']].apply(le.fit_transform)

In [15]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1
914,68,1,0,144,193,1,1,141,0,3.4,1,1
915,57,1,0,130,131,0,1,115,1,1.2,1,1
916,57,0,1,130,236,0,0,174,0,0.0,1,1
917,38,1,2,138,175,0,1,173,0,0.0,2,0

In [16]:
df['zscore_old'] = (df.Oldpeak - df.Oldpeak.mean())/df.Oldpeak.std()

In [19]:
df['zscore_max'] = (df.MaxHR - df.MaxHR.mean())/df.MaxHR.std()

In [20]:
df['zscore_choles'] = (df.Cholesterol - df.Cholesterol.mean())/df.Cholesterol.std()

In [21]:
df['zscore_resting_bp'] = (df.RestingBP - df.RestingBP.mean())/df.RestingBP.std()

In [22]:
df['zscore_age'] = (df.Age - df.Age.mean())/df.Age.std()

In [24]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore_old,zscore_max,zscore_choles,zscore_resting_bp,zscore_age
0,40,1,1,140,289,0,1,172,0,0.0,2,0,-0.831979,1.382175,0.824621,0.410685,-1.432359
1,49,0,2,160,180,0,1,156,0,1.0,1,1,0.105606,0.753746,-0.171867,1.490940,-0.478223
2,37,1,1,130,283,0,2,98,0,0.0,2,0,-0.831979,-1.524307,0.769768,-0.129442,-1.750404
3,48,0,0,138,214,0,1,108,1,1.5,1,1,0.574398,-1.131539,0.138964,0.302660,-0.584238
4,54,1,2,150,195,0,1,122,0,0.0,2,0,-0.831979,-0.581664,-0.034736,0.950812,0.051853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1,0.293123,-0.188897,0.596068,-1.209697,-0.902283
914,68,1,0,144,193,1,1,141,0,3.4,1,1,2.355810,0.164595,-0.053020,0.626736,1.536064
915,57,1,0,130,131,0,1,115,1,1.2,1,1,0.293123,-0.856602,-0.619830,-0.129442,0.369898
916,57,0,1,130,236,0,0,174,0,0.0,1,1,-0.831979,1.460728,0.340090,-0.129442,0.369898
917,38,1,2,138,175,0,1,173,0,0.0,2,0,-0.831979,1.421452,-0.217578,0.302660,-1.644389

In [42]:
df_new = df[((df.zscore_old > -3) &(df.zscore_old < 3)) & ((df.zscore_max > -3) &(df.zscore_max < 3)) & ((df.zscore_choles > -3) &(df.zscore_choles < 3)) & ((df.zscore_resting_bp > -3) &(df.zscore_resting_bp < 3))]

In [28]:
df_new

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,zscore_old,zscore_max,zscore_choles,zscore_resting_bp,zscore_age
0,40,1,1,140,289,0,1,172,0,0.0,2,0,-0.831979,1.382175,0.824621,0.410685,-1.432359
1,49,0,2,160,180,0,1,156,0,1.0,1,1,0.105606,0.753746,-0.171867,1.490940,-0.478223
2,37,1,1,130,283,0,2,98,0,0.0,2,0,-0.831979,-1.524307,0.769768,-0.129442,-1.750404
3,48,0,0,138,214,0,1,108,1,1.5,1,1,0.574398,-1.131539,0.138964,0.302660,-0.584238
4,54,1,2,150,195,0,1,122,0,0.0,2,0,-0.831979,-0.581664,-0.034736,0.950812,0.051853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1,0.293123,-0.188897,0.596068,-1.209697,-0.902283
914,68,1,0,144,193,1,1,141,0,3.4,1,1,2.355810,0.164595,-0.053020,0.626736,1.536064
915,57,1,0,130,131,0,1,115,1,1.2,1,1,0.293123,-0.856602,-0.619830,-0.129442,0.369898
916,57,0,1,130,236,0,0,174,0,0.0,1,1,-0.831979,1.460728,0.340090,-0.129442,0.369898
917,38,1,2,138,175,0,1,173,0,0.0,2,0,-0.831979,1.421452,-0.217578,0.302660,-1.644389

In [38]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

In [54]:
df_work = df_new.drop(['zscore_old', 'zscore_max', 'zscore_choles', 'zscore_resting_bp', 'zscore_age'],axis =1)
df_work

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1
914,68,1,0,144,193,1,1,141,0,3.4,1,1
915,57,1,0,130,131,0,1,115,1,1.2,1,1
916,57,0,1,130,236,0,0,174,0,0.0,1,1
917,38,1,2,138,175,0,1,173,0,0.0,2,0

In [55]:
y = df_work.HeartDisease
X = df_work.drop(['HeartDisease'], axis =1)
X_scale = scale.fit_transform(X)

In [56]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(X, y, stratify=y, random_state = 10)

In [96]:
from sklearn.svm import SVC
model = SVC(C = 2200)
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.8844444444444445

In [102]:
from sklearn.ensemble import BaggingClassifier
bg = BaggingClassifier(
                        base_estimator=model,
                        n_estimators= 100,
                        max_samples=0.8,
                        oob_score= True,
                        random_state=0)
bg.fit(X_train, y_train)
bg.oob_score_

0.8308605341246291

In [103]:
bg.score(X_test, y_test)

0.8755555555555555

In [104]:
from sklearn.tree import DecisionTreeClassifier
model_tree = DecisionTreeClassifier()
model_tree.fit(X_train, y_train)
model_tree.score(X_test, y_test)

0.8177777777777778

In [105]:
bg_tree = BaggingClassifier(
                        base_estimator=model_tree,
                        n_estimators= 100,
                        max_samples=0.8,
                        oob_score= True,
                        random_state=0)
bg_tree.fit(X_train, y_train)
bg_tree.oob_score_

0.8501483679525222

In [106]:
bg_tree.score(X_test, y_test)

0.8888888888888888